variables:
  - name: System.Debug
    value: true

pool:
  vmImage: 'macOs-10.14'

steps:  
  - task: CmdLine@2
    displayName: 'Install Core Dependencies'
    inputs:
      script: |
        yarn install
